// src/components/Footer.vue
<script setup>
import { portfolio } from '../data/portfolio.js'
import IconSet from './IconSet.vue'
const { profile } = portfolio
const year = new Date().getFullYear()
</script>

<template>
  <footer>
    <div class="container">
      <div class="foot-top">
        <span class="font-display foot-brand">GB<span class="text-gradient">.DEV</span></span>
        <div class="foot-links font-mono">
          <a :href="profile.github" target="_blank" rel="noopener"><IconSet name="github" :size="14" />GitHub</a>
          <a :href="profile.linkedin" target="_blank" rel="noopener"><IconSet name="linkedin" :size="14" />LinkedIn</a>
          <a href="mailto:bakkeraganesh@gmail.com"><IconSet name="mail" :size="14" />Email</a>
        </div>
      </div>
      <div class="foot-bottom font-mono">
        <span>© {{ year }} Ganesh Bakkera</span>
        <span>Designed &amp; built with Vue 3 · Three.js · Theatre.js · GSAP</span>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.foot-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 20px;
  flex-wrap: wrap;
  padding-bottom: 24px;
  border-bottom: 1px solid var(--line);
}
.foot-brand { font-size: 1.4rem; font-weight: 700; letter-spacing: 0.1em; }
.foot-links { display: flex; gap: 26px; }
.foot-links a {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: var(--text-dim);
  text-decoration: none;
  font-size: 12px;
  letter-spacing: 0.1em;
  transition: color 0.3s ease;
}
.foot-links a:hover { color: var(--cyan); }
.foot-bottom {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
  padding-top: 24px;
  color: var(--text-faint);
  font-size: 11px;
  letter-spacing: 0.08em;
}
</style>

// components/Footer.jsx
'use client'

import { motion } from 'motion/react'
import { portfolio } from '@/content/portfolio'
import Logo from './ui/Logo'

export default function Footer() {
  const goTop = () => window.scrollTo({ top: 0, behavior: 'smooth' })

  return (
    <motion.footer
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true, margin: '-60px' }}
      transition={{ duration: 0.7 }}
      className="relative border-t border-line"
    >
      <div className="mx-auto flex max-w-6xl flex-col items-center gap-8 px-5 py-12 md:flex-row md:justify-between md:px-8">
        <div className="flex flex-col items-center gap-2">
          <div className="flex items-center gap-2.5">
            <Logo size={34} />
            <span className="font-display text-lg font-extrabold">
              <span className="grad-text">{portfolio.profile.last}</span>
            </span>
          </div>
          <p className="text-xs text-faint">
            © {new Date().getFullYear()} Ganesh Bakkera · Built with Next.js · Tailwind · Motion
          </p>
        </div>

        <div className="flex items-center gap-2">
          <a href={portfolio.profile.github} target="_blank" rel="noopener noreferrer" className="btn btn-ghost px-4 py-2 text-xs">
            GitHub
          </a>
          <a href={portfolio.profile.linkedin} target="_blank" rel="noopener noreferrer" className="btn btn-ghost px-4 py-2 text-xs">
            LinkedIn
          </a>
        </div>

        <button
          onClick={goTop}
          aria-label="Back to top"
          className="group grid h-12 w-12 place-items-center rounded-full border border-line bg-surface shadow-card transition-transform duration-300 hover:-translate-y-1"
        >
          <svg
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="text-mute transition-transform duration-300 group-hover:-translate-y-0.5 group-hover:text-accent"
          >
            <path d="M12 19V5M5 12l7-7 7 7" />
          </svg>
        </button>
      </div>
    </motion.footer>
  )
}
